In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

# 1D to 2d using -1

In [12]:
np.reshape(arr,(2,-1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 1D to 3D array

In [15]:
arr.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
arr.reshape(2,-1,1)

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

# 3D to 1D array

In [20]:
arr3=np.array([[[1],[2],[3],[4]],[[5],[6],[7],[8]]])

In [22]:
arr3.ndim

3

In [24]:
arr3.shape

(2, 4, 1)

In [26]:
arr3.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

# SORTING

In [29]:
x=np.array([22,34,51,12,14,23,5])
x

array([22, 34, 51, 12, 14, 23,  5])

In [38]:
x=np.sort(x)
x

array([ 5, 12, 14, 22, 23, 34, 51])

In [42]:
# for descending order

In [44]:
x[::-1]

array([51, 34, 23, 22, 14, 12,  5])