In [2]:
# Random

In [4]:
import numpy as np
from numpy import random

In [6]:
# randint()
# random.randit(start,end,size=(dimensions))

In [18]:
zx=random.randint(100)

In [20]:
zx

57

In [25]:
# size--->perameter

In [27]:
# 10-----20 :::50

In [29]:
x=random.randint(10,20,size=(5))
x

array([15, 17, 18, 15, 15])

In [31]:
# for 2D array


In [33]:
x=random.randint(10,50,size=(5,4))
x

array([[36, 17, 19, 21],
       [26, 19, 37, 17],
       [34, 25, 44, 31],
       [37, 36, 36, 49],
       [25, 40, 21, 25]])

In [36]:
# rand()-----> 0 to 1

In [50]:
a=random.rand()
a

0.503145628935266

In [54]:
x=random.rand(10)
x

array([0.62535168, 0.77215195, 0.10585327, 0.26261225, 0.74046524,
       0.81235021, 0.66703209, 0.19128157, 0.05766829, 0.55489254])

In [56]:
x=random.rand(2,4) # for 2-D
x

array([[0.20689938, 0.89496082, 0.61475115, 0.35320121],
       [0.23631696, 0.26718565, 0.31905616, 0.02550915]])

In [60]:
# for 3-D
x=random.rand(2,3,1)
x

array([[[0.06480638],
        [0.40857619],
        [0.64134958]],

       [[0.34393079],
        [0.98842343],
        [0.60866026]]])

In [65]:
# random()
# same as rand

In [67]:
# choice

In [75]:
zx=random.choice([1,2,3,4,5])
zx

3

In [80]:
# to make array of choices
zx=random.choice([1,2,3,4,5],size=(2,2))
zx

array([[2, 1],
       [2, 5]])

In [103]:
# random.shuffle()


In [113]:
zx=np.array([1,2,3,23])
random.shuffle(zx)

In [115]:
zx

array([ 3,  2,  1, 23])

In [123]:
# random()
# randint()
# rand()
# choice()b
# shuffle()