# reshape:this is a method that helps us to reshape the shape of data

In [4]:
import numpy as np
arr=np.array([1,2,3,4])

In [6]:
arr.shape

(4,)

In [8]:
arr.ndim

1

In [10]:
# reshape

In [14]:
# objectname.reshape(shape)
# np.reshape(objectname,shape)

In [22]:
np.reshape(arr,(2,2))

array([[1, 2],
       [3, 4]])

In [36]:
arr1=np.array([1,2,3,4,5,6])
np.reshape(arr1,(6,1))


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
# 2D to 1D

In [42]:
arr2=np.array([[1,2,3,4,5,6],[23,454,32,4,2,23]])
arr2


array([[  1,   2,   3,   4,   5,   6],
       [ 23, 454,  32,   4,   2,  23]])

In [44]:
arr2.ndim

2

In [48]:
arr2.shape

(2, 6)

In [85]:
arr2.reshape(12)

array([  1,   2,   3,   4,   5,   6,  23, 454,  32,   4,   2,  23])

In [106]:
arr3=np.array([[1,2,3,4,5,6],[23,454,32,4,2,23]])
q=np.reshape(arr3,-1)
q

array([  1,   2,   3,   4,   5,   6,  23, 454,  32,   4,   2,  23])