In [41]:
import numpy as np

In [43]:
from numpy import random

In [45]:
q=random.uniform(-1,1)
q

-0.29873627638586164

In [47]:
# Generate a 3x3 Numpy array with random floating point numbers between -1 and 1.Compute the absolute value of each element.

In [49]:
w=random.uniform(-1,1,size=(3,3))
w

array([[-0.17238664, -0.75044538,  0.96976914],
       [ 0.17099991, -0.6392153 ,  0.80111056],
       [-0.05581162, -0.75805881, -0.86591507]])

In [51]:
np.absolute(w)

array([[0.17238664, 0.75044538, 0.96976914],
       [0.17099991, 0.6392153 , 0.80111056],
       [0.05581162, 0.75805881, 0.86591507]])

In [53]:
# gernerate a 6x6 numpy array with random integers between 0 and 100 . find the max value in each row and replace with the string 'max'

In [171]:
arr=random.randint(0,100,size=(6,6))
arr = arr.astype("S")
arr

array([[b'68', b'23', b'16', b'60', b'44', b'26'],
       [b'7', b'99', b'17', b'8', b'85', b'73'],
       [b'7', b'75', b'64', b'91', b'55', b'42'],
       [b'39', b'95', b'98', b'92', b'60', b'2'],
       [b'34', b'38', b'53', b'56', b'14', b'58'],
       [b'12', b'45', b'26', b'7', b'37', b'88']], dtype='|S11')

In [183]:
y=np.amax(arr,axis=1)
y

UFuncTypeError: ufunc 'maximum' did not contain a loop with signature matching types (dtype('S11'), dtype('S11')) -> None

In [177]:
w=arr.reshape(-1)

w.dtype

dtype('S11')

In [179]:
for i in y:
    ind=np.where(w==i)
    w[ind]="MAX"

In [181]:
w

array([b'68', b'23', b'16', b'60', b'44', b'26', b'7', b'99', b'17', b'8',
       b'85', b'73', b'7', b'75', b'64', b'91', b'55', b'42', b'39',
       b'95', b'98', b'92', b'60', b'2', b'34', b'38', b'53', b'56',
       b'14', b'58', b'12', b'45', b'26', b'7', b'37', b'88'],
      dtype='|S11')

In [121]:
arr=random.randint(0,100,size=(6,6))
arr

array([[92,  3, 74, 45, 86, 23],
       [42, 74, 46, 49, 26, 29],
       [91, 69, 78, 62, 94, 54],
       [31, 83, 15, 24,  3, 73],
       [12, 36, 53,  1, 31,  5],
       [22, 33, 76, 42, 58, 47]])

In [125]:
for i in arr:
    print(max(i))
    

92
74
94
83
53
76


In [151]:
pq = np.array([12, 23, 3, "ca"], dtype = "S")

In [153]:
pq

array([b'12', b'23', b'3', b'ca'], dtype='|S2')

In [163]:
zx = np.arange(1, 11, dtype = "S")

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.BytesDType'>.

In [185]:
# create a numoy array with the elements["cat","dog","bird","cat","dog","fish"] and then count the occurences of each unique element.

In [187]:
arr=np.array(["cat","dog","bird","cat","dog","fish"])

In [189]:
arr1=np.unique(arr)
arr1

array(['bird', 'cat', 'dog', 'fish'], dtype='<U4')

In [191]:
for i in arr1:
    count=0
    for j in arr:
        if i==j:
            count=count+1
    print(f"the occurence of {i} = {count}") 

the occurence of bird = 1
the occurence of cat = 2
the occurence of dog = 2
the occurence of fish = 1


In [193]:
# define a numpy array containing the numbers 1 through 12 and reshape into 3x4 array .Calculate the standard deviation of each column.

In [205]:
 arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [207]:
np.std(arr,axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [212]:
# generate a 4x4 numpy array with random integers between -50 and 50.Replace the all negative values with 0 and all positive values with 1.

In [256]:
r=random.randint(-50,50,size=(4,4))

In [258]:
r

array([[ 39, -10,  18,  24],
       [-49,  -1,  33, -29],
       [  3, -46, -47,  11],
       [-24,  27, -14, -18]])

In [260]:
oneD=r.reshape(-1)
oneD

array([ 39, -10,  18,  24, -49,  -1,  33, -29,   3, -46, -47,  11, -24,
        27, -14, -18])

In [262]:
zeros=np.where(oneD<0)

In [264]:
zeros

(array([ 1,  4,  5,  7,  9, 10, 12, 14, 15], dtype=int64),)

In [266]:
oneD[zeros]=0
oneD

array([39,  0, 18, 24,  0,  0, 33,  0,  3,  0,  0, 11,  0, 27,  0,  0])

In [268]:
ones=np.where(oneD>0)

In [270]:
oneD[ones]=1

In [272]:
r=oneD.reshape(4,4)
r

array([[1, 0, 1, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 0]])

In [274]:
# create a numpy array with the elements ["apple","banana","cheery","apple","banana"] .Remove duplicates from array  

In [276]:
arr=np.array(["apple","banana","cheery","apple","banana"])

In [278]:
arr

array(['apple', 'banana', 'cheery', 'apple', 'banana'], dtype='<U6')

In [280]:
np.unique(arr)

array(['apple', 'banana', 'cheery'], dtype='<U6')

In [282]:
# define a numpy array containing the numbers 1 through 16 and reshape it into 4x4 array. extract elements in the last column.

In [308]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [326]:
for i in range(4):
    print(arr[i][3])

4
8
12
16


In [329]:
# generate a 5x5 numpy array with random floating point number between 0 and 1. round each element with nearest integer.

In [400]:
arr=random.random(size=(5,5))

In [402]:
arr

array([[0.62790755, 0.58039068, 0.27267597, 0.6326757 , 0.96314951],
       [0.77458724, 0.50670419, 0.38538956, 0.55023059, 0.37738865],
       [0.54199451, 0.14902939, 0.05217771, 0.62055514, 0.4555666 ],
       [0.76665117, 0.99770631, 0.69484876, 0.47889578, 0.43437414],
       [0.64291941, 0.04637366, 0.79658867, 0.01557905, 0.65130905]])

In [404]:
np.round(arr)

array([[1., 1., 0., 1., 1.],
       [1., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [1., 1., 1., 0., 0.],
       [1., 0., 1., 0., 1.]])

In [406]:
# create a numpy array with element ["red","green","blue","red","green","blue"]. replace "red" with "orange".

In [432]:
arr=np.array(["red","green","blue","red","green","blue"])

In [434]:
y=np.size(arr)

In [436]:
for i in range(np.size(arr)):
    if arr[i] == "red":
        arr[i]="orange"
        

In [438]:
arr

array(['orang', 'green', 'blue', 'orang', 'green', 'blue'], dtype='<U5')

In [441]:
# define a numpy aarray number 1 through 20 and reshape it into 5x4 array. compute the sum of each column.

In [443]:
arr=np.arange(1,21).reshape(5,4)

In [445]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [447]:
np.sum(arr,axis=0)

array([45, 50, 55, 60])

In [450]:
# generate a 3x3 numpy array with random integers between 1 and 100 . find the index of max value in array.

In [452]:
arr=random.randint(1,100,size=(3,3))

In [454]:
arr

array([[ 3, 84,  8],
       [49, 87, 26],
       [58, 70, 17]])

In [458]:
np.amax(arr)

87

In [460]:
np.where(arr==np.amax(arr))

(array([1], dtype=int64), array([1], dtype=int64))

In [462]:
help(np.amax)

Help on _ArrayFunctionDispatcher in module numpy:

amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Return the maximum of an array or maximum along an axis.
    
    `amax` is an alias of `~numpy.max`.
    
    See Also
    --------
    max : alias of this function
    ndarray.max : equivalent method



In [464]:
# generate 100 element in 2D array, 10 rows 5 column then in that nd array the elements which are divisible by 2 put 0
# and the elements which are not divisible by 2 put 1, divisible by 2 and 3 both put 2.

In [466]:
arr=random.randint(1,100,size=(10,5))

In [468]:
arr

array([[43, 71, 48, 82, 80],
       [12, 24, 22, 37, 83],
       [22, 50, 70, 39, 88],
       [33,  4, 81, 10,  3],
       [78, 51, 96, 20, 52],
       [ 3, 93, 31, 64, 15],
       [24, 69, 89, 50,  1],
       [53, 20, 23, 45, 67],
       [86, 20, 16,  7, 82],
       [85, 17, 41, 63, 89]])

In [494]:
six=np.where(arr%6==0)

In [496]:
two=np.where(arr%2==0)


In [498]:
one=np.where(arr%2!=0)

In [ ]:
---->pending^